<?php

########################################################################
# Extension Manager/Repository config file for ext: "sfstefan"
#
# Auto generated by Extension Builder 2012-10-04
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'fal_dropbox',
	'description' => 'Provides a DropBox driver for the TYPO3 File Abstraction Layer.',
	'category' => 'plugin',
	'author' => 'Stefan froemken',
	'author_email' => 'firma@sfroemken.de',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>