services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  StefanFroemken\Dropbox\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Configuration/DropboxConfiguration'
      - '../Classes/Response/AccessTokenResponse'
      - '../Classes/TokenProvider/RefreshingTokenProvider'

  # Will be called by GeneralUtility::makeInstance in DropboxClientFactory
  # Do not autowire, as the "Client" class is not part of this dropbox extension.
  StefanFroemken\Dropbox\Client\DropboxClient:
    public: true
    shared: false
    autowire: false

  # Will be called by GeneralUtility::makeInstance in DropboxDriver
  StefanFroemken\Dropbox\Client\DropboxClientFactory:
    public: true

  # Will be called by GeneralUtility::makeInstance in DropboxDriver
  StefanFroemken\Dropbox\Configuration\ExtConf:
    public: true

  # Will be called by GeneralUtility::makeInstance in ExtractorRegistry
  StefanFroemken\Dropbox\Extractor\ImageExtractor:
    public: true

  # Will be called by GeneralUtility::makeInstance in DropboxDriver
  StefanFroemken\Dropbox\Helper\FlashMessageHelper:
    public: true

  # Will be called by GeneralUtility::makeInstance in ProcessorRegistry
  StefanFroemken\Dropbox\Resource\Processing\ImageProcessing:
    public: true
