services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  StefanFroemken\Dropbox\:
    resource: '../Classes/*'

  # Will be called by GeneralUtility::makeInstance in TYPO3 StorageRepository
  StefanFroemken\Dropbox\Driver\DropboxDriver:
    public: true
    calls:
      - setFlashMessageHelper: ['StefanFroemken\Dropbox\Helper\FlashMessageHelper']

  # Will be called by GeneralUtility::makeInstance in DropboxDriver and DropboxStatusElement
  StefanFroemken\Dropbox\Service\AutoRefreshingDropboxTokenService:
    autowire: false
    autoconfigure: false
    public: true

  StefanFroemken\Dropbox\Response\AccessTokenResponse:
    autowire: false
    autoconfigure: false
    public: true

