# Adapted from https://github.com/TYPO3GmbH/blog/blob/master/.github/workflows/ci.yml
name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        typo3: [^10.4]
        php: ['7.2', '7.3', '7.4']

    services:
      mysql:
        image: mysql:5.6
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP ${{ matrix.php }}, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, dom, zip, mysql

      - name: Start mysql service
        run: sudo /etc/init.d/mysql start

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies with typo3/cms-core:${{ matrix.typo3 }}
        run: |
          composer require typo3/cms-core:${{ matrix.typo3 }} --no-progress
          composer require typo3/cms-extensionmanager:${{ matrix.typo3 }} --no-progress
          # SF: Remove next line, if version 2.13.2 was released
          # Issue: https://github.com/Nimut/testing-framework/issues/136
          composer require doctrine/dbal:2.10.4 doctrine/cache:^1.0 --no-progress
          git checkout composer.json

      - name: php-cs-fixer
        run: composer ci:php:fixer

      - name: Lint PHP
        run: composer ci:php:lint

      - name: Unit Tests
        run: composer ci:tests:unit

      - name: Functional Tests
        env:
          typo3DatabaseName: test
          typo3DatabaseUsername: root
          typo3DatabasePassword: password
          typo3DatabaseHost: 127.0.0.1
          typo3DatabasePort: ${{ job.services.mysql.ports['3306'] }}
        run: |
          composer ci:tests:functional
